#!/bin/bash
# Setup script for TensorProx validator capabilities
#
# For ROOT users:
#   No setup needed! Root already has all required capabilities.
#   Just run the validator directly.
#
# For NON-ROOT users:
#   Run this script ONCE with sudo to configure the validator machine:
#     sudo bash scripts/setup-validator-caps.sh
#
# This script:
# 1. Sets CAP_NET_RAW capability on Python for raw packet sending
# 2. Installs sudoers rules for non-root users to manage WireGuard tunnels

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SUBNET_DIR="$(dirname "$SCRIPT_DIR")"

echo "=== TensorProx Validator Setup ==="

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "ERROR: This script must be run as root (use sudo)"
    echo ""
    echo "If you plan to run the validator AS ROOT, no setup is needed."
    echo "Root already has all required capabilities."
    exit 1
fi

# Detect who will run the validator (check SUDO_USER or default to current user)
VALIDATOR_USER="${SUDO_USER:-root}"
echo "Detected validator user: $VALIDATOR_USER"

# If validator will run as root, minimal setup needed
if [ "$VALIDATOR_USER" = "root" ]; then
    echo ""
    echo "Validator will run as root - no special setup required!"
    echo "Root already has all capabilities (CAP_NET_RAW, network admin, etc.)"
    echo ""
    echo "You can start the validator directly."
    exit 0
fi

echo ""
echo "Setting up for non-root user: $VALIDATOR_USER"

# Find Python binary used by the venv
PYTHON_REAL=$(readlink -f "$SUBNET_DIR/.venv/bin/python" 2>/dev/null)
if [ -z "$PYTHON_REAL" ]; then
    # Fallback: try common Python paths
    for py in /usr/bin/python3.12 /usr/bin/python3.11 /usr/bin/python3.10 /usr/bin/python3; do
        if [ -f "$py" ]; then
            PYTHON_REAL="$py"
            break
        fi
    done
fi

if [ -z "$PYTHON_REAL" ] || [ ! -f "$PYTHON_REAL" ]; then
    echo "ERROR: Python binary not found"
    exit 1
fi

echo "Python binary: $PYTHON_REAL"

# Step 1: Set CAP_NET_RAW capability for raw packet sending
echo ""
echo "1. Setting CAP_NET_RAW capability on Python..."
setcap 'cap_net_raw+eip' "$PYTHON_REAL"
echo "   Done: $(getcap "$PYTHON_REAL")"

# Step 2: Install sudoers rules for non-root validator operation
echo ""
echo "2. Installing sudoers rules for non-root validator operations..."
SUDOERS_FILE="/etc/sudoers.d/tensorprox"
cat > "$SUDOERS_FILE" << EOF
# TensorProx validator sudoers rules
# Allows non-root users to manage audit tunnels and raw packet capabilities
# Generated by setup-validator-caps.sh

# CAP_NET_RAW capability management (auto-set on validator restart)
ALL ALL=(root) NOPASSWD: /usr/sbin/setcap cap_net_raw+eip /usr/bin/python3.10
ALL ALL=(root) NOPASSWD: /usr/sbin/setcap cap_net_raw+eip /usr/bin/python3.11
ALL ALL=(root) NOPASSWD: /usr/sbin/setcap cap_net_raw+eip /usr/bin/python3.12
ALL ALL=(root) NOPASSWD: /usr/sbin/setcap cap_net_raw+eip /usr/bin/python3

# WireGuard tunnel management for audit traffic
ALL ALL=(root) NOPASSWD: /usr/bin/wg
ALL ALL=(root) NOPASSWD: /usr/bin/wg-quick
ALL ALL=(root) NOPASSWD: /sbin/ip link *
ALL ALL=(root) NOPASSWD: /sbin/ip addr *
ALL ALL=(root) NOPASSWD: /sbin/ip route *
ALL ALL=(root) NOPASSWD: /usr/sbin/sysctl *
EOF
chmod 440 "$SUDOERS_FILE"
echo "   Done: Sudoers rules installed at $SUDOERS_FILE"

# Verify setup
echo ""
echo "=== Setup Complete ==="
echo ""
echo "Capabilities: $(getcap "$PYTHON_REAL")"
echo ""
echo "The validator can now be run as user '$VALIDATOR_USER'."
echo "Start/restart with: pm2 restart tensorprox-validator"
